stages:          # List of stages for jobs, and their order of execution
  - build

build:
  image: docker:19.03.12
  stage: build
  services:
    - docker:19.03.12-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/tronit/lincare/licare-ordering-app-ionic/licare-ordering-app-ionic-develop-$CI_COMMIT_REF_NAME:latest .
    - docker push $CI_REGISTRY/tronit/lincare/licare-ordering-app-ionic/licare-ordering-app-ionic-develop-$CI_COMMIT_REF_NAME:latest
  when: manual